spring:
  devtools:
    restart:
      enabled: 'true'
      poll-interval: '2s'
      quiet-period: '1s'
      additional-paths:
        - src/main/kotlin/

server:
  port: 8080

management:
  server.port: 8080
  endpoints:
    web:
      exposure:
        include: info, health
